version: "3.8"

services:
  online_app:
    build:
      context: .
    container_name: online_app
    ports:
      - "5173:80"  # Expose container port 80 (Nginx) to host port 5173
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - online_app

networks:
  online_shop:
    driver: bridge
